fos_elastica:
    clients:
        default:
            hosts: ["http://elasticsearch:9200"]
            username: "elastic"
            password: "admin"
    indexes:
        station:
            properties:
                name: { type: text }
                createdAt: { type: date }
                updatedAt: { type: date }
                address:
                    type: object
                    properties:
                        streetLine1: { type: text }
                        streetLine2: { type: text }
                        streetLine3: { type: text }
                        city: { type: text }
                        state: { type: text }
                        postalCode: { type: text }
                        country: { type: text }
                        latitude: { type: float }
                        longitude: { type: float }
            persistence:
                driver: orm
                model: App\Entity\Station
                provider: ~
                finder: ~
                elastica_to_model_transformer:
                    ignore_missing: true
